#!/bin/sh

# This script requires a Java virtual machine version 6 or higher and
# a Java webstart (javaws) application.

# ---
# This launcher script is licensed under the following MIT/zlib-style
# license:
# 
# Copyright (c) 2015-2016 Jordan Irwin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# ---

# ---
# Stendhal is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# ---

set_webstart() {
  webstart=$(command -v $1 2>&1 /dev/null)
  if [ -x "${webstart}" ]; then
    return 1
  fi
  
  return 0
}

# Location of Stendhal's webstart application.
url=https://arianne-project.org/jws/stendhal.jnlp

# Variations of the Java Webstart command in preferred order.
cmd_list="javaws itweb-javaws"

for ws in ${cmd_list}; do
  set_webstart ${ws}
  if [ $? -ne 0 ]; then
    break
  fi
done

if [ ! -x "${webstart}" ]; then
  echo "Fatal error: Java webstart not found."
  echo "Recognized webstart commands: ${cmd_list}"
  exit 1
fi

echo "Connecting to ${url}..."
${webstart} "${url}"

